easy_admin:
    site_name: 'Aes Sidhe Administration'
    
    design:
        menu:
            - { entity: 'User', icon: 'user-circle' }
            - { entity: 'Character', icon: 'user' }
    
    list:
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
            
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - roles
                    - isActive
        Character:
            class: App\Entity\Character
            list:
                fields:
                    - id
                    - firstName
                    - lastName
                    - nickname
                    - { property: 'image', type: 'image', base_path: '/images/' }
            show:
                fields:
                    - id
                    - firstName
                    - lastName
                    - nickname
                    - { property: 'image', type: 'image', base_path: '/images/' }
