swiftmailer:
    url:       '%MAILER_URL%'
    spool:     { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false