swiftmailer:
    #url: '%env(MAILER_URL)%'
    # spool: { type: 'memory' }
    transport:        gmail
    username:         aessidhemailer@gmail.com
    password:         XXX
    host:             localhost
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false